# Replace the "❯" symbol in the prompt with "➜"
[character]      # The name of the module we are confguring is "character"
success_symbol = "[➜](bold green)"     # The "symbol" segment is being set to "➜"
error_symbol = "[✗](bold red)"
vicmd_symbol = "[←](bold blue)"

[kubernetes]
disabled = false
symbol = "⛵ "

[username]
format = "[$user]($style) on "
