#!/bin/bash
# adapted from tb01110100's bspwm config

# bspwm options
bspc config border_width 1
bspc config normal_border_color "#2b2b2b"
bspc config active_border_color "#2b2b2b"
bspc config focused_border_color "#ffbb00"
bspc config window_gap 5
bspc config top_padding 15
bspc config left_padding 15
bspc config right_padding 15

if [[ $(bspc query -M | wc -l) -eq 2 ]]; then
	monitor_one=$(bspc query -M | head -n 1)
	monitor_two=$(bspc query -M | tail -n 1)
	bspc config -m ^1 bottom_padding 60
	bspc config -m ^2 bottom_padding 15
	# set up tags
	bspc monitor $monitor_one -d web dev term
	bspc monitor $monitor_two -d im media misc
	bspc rule -a firefox desktop=^1
	bspc rule -a qutebrowser desktop=^1

else
	monitor=$(bspc query -M | head -n 1)
	bspc config bottom_padding 60
	# set up tags
	bspc monitor $monitor -d im web dev term media misc
	bspc rule -a qutebrowser desktop=^2
	bspc rule -a firefox desktop=^2
fi


bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true

# set up some rules
bspc rule -a feh floating=on
bspc rule -a Steam floating=on
bspc rule -a mpv floating=on desktop=^5
bspc rule -a lxappearance floating=on
bspc rule -a pcmanfm floating=on
bspc rule -a xfburn floating=on
bspc rule -a zathura floating=on
bspc rule -a xfontsel floating=on
bspc rule -a pavucontrol floating=on

# start sxhkd
sxhkd &

# start bar
bard &
