#!/bin/bash

# bspwm options
bspc config border_width 1
bspc config normal_border_color "#272822"
bspc config active_border_color "#f9f8f5"
bspc config focused_border_color "#f4bf75"
bspc config window_gap 5
bspc config top_padding 15
bspc config left_padding 15
bspc config right_padding 15
bspc config bottom_padding 15

if [[ $(bspc query -M | wc -l) -eq 2 ]]; then
	monitor_one=$(bspc query -M | head -n 1)
	monitor_two=$(bspc query -M | tail -n 1)
	# set up tags
	bspc monitor $monitor_one -d i ii iii iv v vi vii ix x
	bspc monitor $monitor_two -d xi
	~/.screenlayout/dual.sh &

else
	monitor=$(bspc query -M | head -n 1)
	# set up tags
        bspc monitor $monitor -d i ii iii iv v vi vii ix x
fi


bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true

# set up some rules
bspc rule -a pcmanfm floating=on
bspc rule -a xfontsel floating=on
bspc rule -a pavucontrol floating=on

# set wallpaper
hsetroot -fill /home/filip/dotfiles/bspwm/.config/bspwm/wallhaven-182976.jpg &
# start other programs
sxhkd &
compton --config ~/.compton.conf -b &
unclutter &

