#!/bin/bash

# bspwm options
bspc config border_width 1
bspc config normal_border_color "#1d1f21"
bspc config active_border_color "#1d1f21"
bspc config focused_border_color "#ecebec"
bspc config urgent_border_color "#912226"
bspc config window_gap 15
bspc config top_padding 15
bspc config left_padding 15
bspc config right_padding 15
bspc config bottom_padding 15

if [[ $(bspc query -M | wc -l) -eq 2 ]]; then
	monitor_one=$(bspc query -M | head -n 1)
	monitor_two=$(bspc query -M | tail -n 1)
	# set up tags
	bspc monitor $monitor_one -d i ii iii iv
	bspc monitor $monitor_two -d v
	~/.screenlayout/dual.sh &

else
	monitor=$(bspc query -M | head -n 1)
	# set up tags
        bspc monitor $monitor -d i ii iii iv v
fi


bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true

# set up some rules
bspc rule -a pcmanfm floating=on
bspc rule -a xfontsel floating=on
bspc rule -a pavucontrol floating=on

# set wallpaper
setroot ~/.config/bspwm/wallhaven-32339.jpg  --on 1 &
# start other programs
sxhkd &
compton --config ~/.compton.conf -b &
unclutter &

# start bottombar
bottombar &
