#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# exports
export GOPATH=$HOME/git/go
export PATH=$HOME/.bin:$GOPATH/bin:$HOME/.cabal/bin:$PATH
export EDITOR='nvim'
export PAGER='less'

alias vim='nvim'
