#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# exports
export GOPATH=$HOME/git/go
export PATH=$HOME/.bin:$GOPATH/bin:$HOME/.cabal/bin:$PATH
export EDITOR='nvim'
export PAGER='less'

alias vim='nvim'

# dircolors
#eval $(dircolors ~/.dircolors)

# Base16 Shell
BASE16_SHELL="$HOME/.config/base16-shell/base16-tomorrow.dark.sh"
[[ -s $BASE16_SHELL ]] && source $BASE16_SHELL
