#!/bin/bash

# ONE DARK
######################
BLACK='#282c34'
RED='#e06c75'
GREEN='#98c379'
YELLOW='#e5c07b'
BLUE='#61afef'
MAGENTA='#c678dd'
CYAN='#56b6c2'
LIGHT_GREY='#abb2bf'
BRIGHT_BLACK='#3e4452'
BRIGHT_RED='#be5046'
BRIGHT_GREEN='#98c379'
BRIGHT_YELLOW='#d19a66'
BRIGHT_BLUE='#61afef'
BRIGHT_MAGENTA='#c678dd'
BRIGHT_CYAN='#56b6c2'
WHITE='#5c6370'

# GRUVBOX
######################
#BLACK='#1d2021'
#RED='#cc241d'
#GREEN='#98971a'
#YELLOW='#d79921'
#BLUE='#458588'
#MAGENTA='#b16286'
#CYAN='#689d6a'
#LIGHT_GREY='#a89984'
#GREY='#928374'
#BRIGHT_RED='#fb4934'
#BRIGHT_GREEN='#b8bb26'
#BRIGHT_YELLOW='#fabd2f'
#BRIGHT_BLUE='#83a598'
#BRIGHT_MAGENTA='d3869b'
#BRIGHT_CYAN='#8ec07c'
#WHITE='#ebdbb2'

# DRACULA
######################
#BLACK='#000000'
#GREY='#4D4D4D'
#RED='#FF5555'
#BRIGHT_RED='#FF6E67'
#GREEN='#50FA7B'
#BRIGHT_GREEN='#5AF78E'
#YELLOW='#F1FA8C'
#BRIGHT_YELLOW='#F4F99D'
#BLUE='#BD93F9'
#BRIGHT_BLUE='#CAA9FA'
#MAGENTA='#FF79C6'
#BRIGHT_MAGENTA='#FF92D0'
#CYAN='#8BE9FD'
#BRIGHT_CYAN='#9AEDFE'
#LIGHT_GREY='#BFBFBF'
#WHITE='#E6E6E6'

# SOLARIZED
######################
#BLACK='#073642'
#GREY='#002b36'
#RED='#dc322f'
#BRIGHT_RED='#cb4b16'
#GREEN='#859900'
#BRIGHT_GREEN='#586e75'
#YELLOW='#b58900'
#BRIGHT_YELLOW='#657b83'
#BLUE='#268bd2'
#BRIGHT_BLUE='#839496'
#MAGENTA='#d336682'
#BRIGHT_MAGENTA='#6c71c4'
#CYAN='#2aa198'
#BRIGHT_CYAN='#93a1a1'
#LIGHT_GREY='#eee8d5'
#WHITE='#fdf6e3'

# NORD
######################
#BLACK='#3B4252'
#RED='#BF616A'
#GREEN='#A3BE8C'
#YELLOW='#EBCB8B'
#BLUE='#81A1C1'
#MAGENTA='#B48EAD'
#CYAN='#88C0D0'
#LIGHT_GRAY='#E5E9F0'
#GRAY='#4C566A'
#BRIGHT_RED='#BF616A'
#BRIGHT_GREEN='#A3BE8C'
#BRIGHT_YELLOW='#EBCB8B'
#BRIGHT_BLUE='#81A1C1'
#BRIGHT_MAGENTA='#B48EAD'
#BRIGHT_CYAN='#8FBCBB'
#WHITE='#ECEFF4'

# OCEANICNEXT
######################
#BLACK="#1a2b34" # Base 00 - Black
#RED="#ee5d64" # Base 08 - Red
#GREEN="#98c892" # Base 0B - Green
#YELLOW="#fbc959" # Base 0A - Yellow
#BLUE="#6498ce" # Base 0D - Blue
#MAGENTA="#C693C6" # Base 0E - Magenta
#CYAN="#5ab3b4" # Base 0C - Cyan
#LIGHT_GRAY="#c0c5ce" # Base 05 - White
#GRAY="#65737e" # Base 03 - Bright Black
#BRIGHT_RED="#ee5d64" # Base 08 - Red
#BRIGHT_GREEN="#98c892" # Base 0B - Green
#BRIGHT_YELLOW="#fbc959" # Base 0A - Yellow
#BRIGHT_BLUE="#6498ce" # Base 0D - Blue
#BRIGHT_MAGENTA="#C693C6" # Base 0E - Magenta
#BRIGHT_CYAN="#5ab3b4" # Base 0C - Cyan
#WHITE="#cdd3de" # Base 07 - Bright White

# MONOKAI
######################

#BLACK="#272822" # Base 00 - Black
#RED="#f92672" # Base 08 - Red
#GREEN="#a6e22e" # Base 0B - Green
#YELLOW="#f4bf75" # Base 0A - Yellow
#BLUE="#66d9ef" # Base 0D - Blue
#MAGENTA="#ae81ff" # Base 0E - Magenta
#CYAN="#a1efe4" # Base 0C - Cyan
#LIGHT_GRAY="#f8f8f2" # Base 05 - White
#GRAY="#75715e" # Base 03 - Bright Black
#BRIGHT_RED="$RED" # Base 08 - Red
#BRIGHT_GREEN="$GREEN" # Base 0B - Green
#BRIGHT_YELLOW="$YELLOW" # Base 0A - Yellow
#BRIGHT_BLUE="$BLUE" # Base 0D - Blue
#BRIGHT_MAGENTA="$MAGENTA" # Base 0E - Magenta
#BRIGHT_CYAN="$CYAN" # Base 0C - Cyan
#WHITE="#f9f8f5" # Base 07 - Bright White
