#!/bin/zsh

TIME=5
WIDTH=180
XPOS=1720
YPOS=20
BG="#141414"
FG="#ffbb00"
FN="-lucy-tewi-medium-r-normal--11-90-75-75-p-58-iso10646-1"

echo 'Hello world' |
  dzen2 -p $TIME -w $WIDTH -x $XPOS -y $YPOS -bg $BG -fg $FG -fn $FN
