#!/bin/bash

#FONT="-lucy-tewi-medium-*-*--11-*-*-*-*-*-*-*"
FONT="-xos4-terminus-medium-r-normal--12-120-72-72-c-60-iso8859-1"
BG="#1d1f21"
FG="#81a2be"
SELECT_BG=$FG
SELECT_FG=$BG
LINES=20
WIDTH=250
PROMPT=">>>"
X=15 #x offset
Y=31 #y offset
OPACITY=0.8

dmenu_run -fn $FONT -nb $BG -nf $FG -sb $SELECT_BG -sf $SELECT_FG -l $LINES -w $WIDTH -p $PROMPT -x $X -y $Y -o $OPACITY

