#!/bin/sh

mopidystat=$(mpc | tail -n 2 | head -n 1 | awk '{print $1}' | tr -d '[]')
spotifystat=$(playerctl status)
if [[ -z $(mpc) && -z $(playerctl status) ]]; then
	echo "p player not running"
elif [[  $mopidystat == "paused" || $spotifystat == "Paused" ]]; then
	echo "p paused"
else
	if [[ -z $(mpc) ]]; then
		echo "p $(playerctl metadata xesam:artist) - $(playerctl metadata xesam:title)"
	else
		echo "p " $(mpc current)
	fi
fi
